// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnwr-DBoBXf63NyIJgS9j9OxDyoNF3qQc',
    appId: '1:763734429560:web:3e6b11ef673932e893c28d',
    messagingSenderId: '763734429560',
    projectId: 'esthetica-56286',
    authDomain: 'esthetica-56286.firebaseapp.com',
    storageBucket: 'esthetica-56286.appspot.com',
    measurementId: 'G-64S9SXZTVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhv76UGaeVuefWUVXTLPoGUNiESRE_2kc',
    appId: '1:763734429560:android:152c17a863051fc293c28d',
    messagingSenderId: '763734429560',
    projectId: 'esthetica-56286',
    storageBucket: 'esthetica-56286.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJW_ocdK565SsEOrHIlZXGXkpoJ0hhqtQ',
    appId: '1:763734429560:ios:0452c0df1696aaef93c28d',
    messagingSenderId: '763734429560',
    projectId: 'esthetica-56286',
    storageBucket: 'esthetica-56286.appspot.com',
    iosBundleId: 'com.example.estheticaWebb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJW_ocdK565SsEOrHIlZXGXkpoJ0hhqtQ',
    appId: '1:763734429560:ios:3e5a6529d97771c793c28d',
    messagingSenderId: '763734429560',
    projectId: 'esthetica-56286',
    storageBucket: 'esthetica-56286.appspot.com',
    iosBundleId: 'com.example.estheticaWebb.RunnerTests',
  );
}
